"""Add git fields to Project

Revision ID: 415068d06579
Revises: 4248b3005538
Create Date: 2025-12-09 19:26:38.668967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415068d06579'
down_revision = '4248b3005538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_repo_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('git_remote_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('auto_detect_git', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('auto_detect_git')
        batch_op.drop_column('git_remote_url')
        batch_op.drop_column('git_repo_path')

    # ### end Alembic commands ###
