"""Initial schema

Revision ID: 4248b3005538
Revises: 
Create Date: 2025-12-09 14:40:25.784620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4248b3005538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('last_analyzed', sa.DateTime(), nullable=True),
    sa.Column('total_analyses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('cyclomatic_complexity', sa.Float(), nullable=True),
    sa.Column('maintainability_index', sa.Float(), nullable=True),
    sa.Column('lines_of_code', sa.Integer(), nullable=True),
    sa.Column('comment_density', sa.Float(), nullable=True),
    sa.Column('duplication_percentage', sa.Float(), nullable=True),
    sa.Column('avg_name_length', sa.Float(), nullable=True),
    sa.Column('max_nesting_depth', sa.Integer(), nullable=True),
    sa.Column('avg_nesting_depth', sa.Float(), nullable=True),
    sa.Column('cognitive_complexity', sa.Integer(), nullable=True),
    sa.Column('avg_function_length', sa.Float(), nullable=True),
    sa.Column('max_function_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['project_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_analyses')
    op.drop_table('project_files')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
